[package]
name = "command_binary"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
glob = { workspace = true }
music_dump_lib = { workspace = true }
anyhow = { workspace = true }